repos:
  # Rust
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --fix --allow-staged --allow-dirty -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-test
        name: cargo test
        entry: cargo test --all
        language: system
        pass_filenames: false
        types: [rust]

  # Documentation
  - repo: local
    hooks:
      - id: gen-stdlib-doc
        name: gen-stdlib-doc
        entry: python3 scripts/gen-stdlib-doc.py
        language: system
        pass_filenames: false
        files: runtime/libpipit/include/std_actors\.h

  # C++
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    hooks:
      - id: clang-format
        types_or: [c, c++]
        exclude: third_party/

  # Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        args: ["--fix"]
